import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Dashboard } from "../components/Dashboard";
import { Search } from "../components/Search";

const Home: NextPage = () => {
  const [address, setAddress] = useState("eezzy.eth");

  return (
    <div>
      <Head>
        <title>Seer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Search props={{ address, setAddress }} />
      <Dashboard address={address} />
    </div>
  );
};

export default Home;
